from __future__ import annotations

import json

from repo_detective.models import AgentReport


def render_markdown(report: AgentReport) -> str:
    stack = ", ".join(report.stack)
    lines = [
        "# Repo Detective Report",
        "",
        f"- **Health score:** {report.score}/100",
        f"- **Files scanned:** {report.files_scanned}",
        f"- **Detected stack:** {stack}",
        "",
        "## Findings",
        "",
    ]
    if not report.findings:
        lines.append("No suspicious clues found. The repository looks tidy.")
    else:
        lines.extend(
            f"- **{finding.severity.upper()}** `{finding.category}` at `{finding.location}` — {finding.message}"
            for finding in report.findings
        )
    lines.extend(["", "## Recommended actions", ""])
    lines.extend(f"{index}. {action}" for index, action in enumerate(report.actions, start=1))
    lines.extend(["", "---", "Generated by Repo Detective Agent.", ""])
    return "\n".join(lines)


def render_json(report: AgentReport) -> str:
    return json.dumps(report.to_dict(), indent=2, ensure_ascii=False, default=str) + "\n"
